on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write
  pull-requests: write

name: Release Please

env:
  NODE_ENV: production

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      twine-core--tag_name: ${{ steps.release.outputs.twine-core--tag_name }}
      twine-core--release_created: ${{ steps.release.outputs.twine-core--release_created }}
      twine-builder--tag_name: ${{ steps.release.outputs.twine-builder--tag_name }}
      twine-builder--release_created: ${{ steps.release.outputs.twine-builder--release_created }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
      - name: Print release outputs for debugging
        continue-on-error: true
        run: |
          echo "Release outputs:"
          echo "${{ toJson(steps.release.outputs) }}"

  release-twine-core:
    if: ${{ needs.release-please.outputs.twine-core--release_created }}
    name: Publish twine-core to npmjs

    runs-on: ubuntu-latest
    needs: release-please

    steps:
      - uses: actions/checkout@v4
      - name: Change working directory to packages/twine-core
        run: cd packages/twine-core
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
